// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThalesApi.Domain.DB;

#nullable disable

namespace ThalesApi.Domain.Migrations
{
    [DbContext(typeof(ThalesContext))]
    [Migration("20250301210139_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThalesApi.Domain.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("creationAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            image = "https://picsum.photos/640/480/?image=639",
                            name = "Technology",
                            slug = "fugit",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            image = "https://picsum.photos/640/480/?image=456",
                            name = "Clothes",
                            slug = "facilis",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            image = "https://picsum.photos/640/480/?image=522",
                            name = "Food",
                            slug = "vitae",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            image = "https://picsum.photos/640/480/?image=255",
                            name = "House",
                            slug = "est",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            image = "https://picsum.photos/640/480/?image=270",
                            name = "Sport",
                            slug = "sapiente",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        });
                });

            modelBuilder.Entity("ThalesApi.Domain.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("creationAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 82,
                            slug = "tenetur",
                            title = "Rustic Steel Pants",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 2,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 54,
                            slug = "eos",
                            title = "Awesome Granite Gloves",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 3,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 46,
                            slug = "earum",
                            title = "Rustic Concrete Sausages",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 4,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 18,
                            slug = "amet",
                            title = "Incredible Fresh Bike",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 5,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 28,
                            slug = "adipisci",
                            title = "Intelligent Frozen Soap",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 6,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 79,
                            slug = "voluptas",
                            title = "Tasty Concrete Car",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 7,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 31,
                            slug = "dolorem",
                            title = "Practical Frozen Sausages",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 8,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 49,
                            slug = "commodi",
                            title = "Gorgeous Concrete Gloves",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 9,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 30,
                            slug = "magni",
                            title = "Rustic Frozen Towels",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 10,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 65,
                            slug = "optio",
                            title = "Small Frozen Pants",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 11,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 64,
                            slug = "reprehenderit",
                            title = "Incredible Concrete Computer",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 12,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 16,
                            slug = "at",
                            title = "Fantastic Cotton Chicken",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 13,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 45,
                            slug = "rem",
                            title = "Small Plastic Ball",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 14,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 59,
                            slug = "quasi",
                            title = "Fantastic Granite Chicken",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 15,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 41,
                            slug = "vero",
                            title = "Generic Cotton Car",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 16,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 35,
                            slug = "repellendus",
                            title = "Awesome Plastic Sausages",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 17,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 67,
                            slug = "non",
                            title = "Handmade Rubber Soap",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 18,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 95,
                            slug = "repudiandae",
                            title = "Practical Plastic Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 19,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 82,
                            slug = "cum",
                            title = "Practical Steel Chicken",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 20,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 59,
                            slug = "praesentium",
                            title = "Rustic Wooden Soap",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 21,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 63,
                            slug = "tempora",
                            title = "Licensed Steel Cheese",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 22,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 33,
                            slug = "consequatur",
                            title = "Generic Granite Gloves",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 23,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 54,
                            slug = "dolore",
                            title = "Awesome Cotton Computer",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 24,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 65,
                            slug = "eum",
                            title = "Intelligent Fresh Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 25,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 57,
                            slug = "saepe",
                            title = "Handcrafted Concrete Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 26,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 54,
                            slug = "eos",
                            title = "Small Steel Tuna",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 27,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 73,
                            slug = "et",
                            title = "Gorgeous Concrete Table",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 28,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 92,
                            slug = "vitae",
                            title = "Ergonomic Cotton Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 29,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 40,
                            slug = "cum",
                            title = "Handmade Metal Cheese",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 30,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 27,
                            slug = "molestiae",
                            title = "Ergonomic Cotton Table",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 31,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 21,
                            slug = "veritatis",
                            title = "Handmade Cotton Pants",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 32,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 23,
                            slug = "aut",
                            title = "Generic Granite Chips",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 33,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 59,
                            slug = "unde",
                            title = "Generic Fresh Chips",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 34,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 63,
                            slug = "culpa",
                            title = "Refined Fresh Chicken",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 35,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 76,
                            slug = "voluptatem",
                            title = "Sleek Rubber Sausages",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 36,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 74,
                            slug = "necessitatibus",
                            title = "Ergonomic Cotton Hat",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 37,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 80,
                            slug = "dicta",
                            title = "Sleek Wooden Car",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 38,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 80,
                            slug = "est",
                            title = "Incredible Plastic Soap",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 39,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 81,
                            slug = "consequatur",
                            title = "Practical Wooden Chair",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 40,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 42,
                            slug = "cupiditate",
                            title = "Incredible Fresh Ball",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 41,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 56,
                            slug = "facere",
                            title = "Rustic Metal Soap",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 42,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 62,
                            slug = "mollitia",
                            title = "Handmade Granite Chips",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 43,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 71,
                            slug = "architecto",
                            title = "Tasty Rubber Ball",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 44,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 85,
                            slug = "quia",
                            title = "Small Plastic Chair",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 45,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 84,
                            slug = "nihil",
                            title = "Rustic Rubber Table",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 46,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 90,
                            slug = "ut",
                            title = "Practical Soft Bike",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 47,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 83,
                            slug = "aliquam",
                            title = "Licensed Plastic Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 48,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 90,
                            slug = "inventore",
                            title = "Tasty Soft Soap",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 49,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 92,
                            slug = "voluptates",
                            title = "Fantastic Cotton Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 50,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 53,
                            slug = "qui",
                            title = "Generic Rubber Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 51,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 89,
                            slug = "placeat",
                            title = "Small Fresh Pants",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 52,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 40,
                            slug = "et",
                            title = "Refined Fresh Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 53,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 40,
                            slug = "voluptas",
                            title = "Handcrafted Wooden Hat",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 54,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 95,
                            slug = "explicabo",
                            title = "Small Steel Towels",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 55,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 77,
                            slug = "animi",
                            title = "Awesome Wooden Computer",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 56,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 71,
                            slug = "molestiae",
                            title = "Gorgeous Concrete Mouse",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 57,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 91,
                            slug = "nam",
                            title = "Small Soft Chair",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 58,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 64,
                            slug = "ea",
                            title = "Generic Granite Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 59,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 19,
                            slug = "illum",
                            title = "Incredible Fresh Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 60,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 56,
                            slug = "dicta",
                            title = "Rustic Fresh Chips",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 61,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 31,
                            slug = "et",
                            title = "Handmade Granite Hat",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 62,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 46,
                            slug = "explicabo",
                            title = "Awesome Concrete Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 63,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 74,
                            slug = "sed",
                            title = "Incredible Frozen Chips",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 64,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 41,
                            slug = "ipsum",
                            title = "Sleek Soft Chips",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 65,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 66,
                            slug = "dignissimos",
                            title = "Refined Soft Bike",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 66,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 19,
                            slug = "et",
                            title = "Licensed Concrete Chips",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 67,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 38,
                            slug = "rerum",
                            title = "Handmade Rubber Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 68,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 28,
                            slug = "alias",
                            title = "Refined Frozen Hat",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 69,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 43,
                            slug = "vel",
                            title = "Gorgeous Granite Table",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 70,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 23,
                            slug = "occaecati",
                            title = "Handmade Rubber Bike",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 71,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 72,
                            slug = "ipsam",
                            title = "Fantastic Wooden Cheese",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 72,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 29,
                            slug = "expedita",
                            title = "Intelligent Frozen Salad",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 73,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 78,
                            slug = "rerum",
                            title = "Incredible Cotton Gloves",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 74,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 47,
                            slug = "explicabo",
                            title = "Intelligent Concrete Cheese",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 75,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 54,
                            slug = "rerum",
                            title = "Intelligent Granite Pants",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 76,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 31,
                            slug = "eos",
                            title = "Practical Fresh Computer",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 77,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 41,
                            slug = "facere",
                            title = "Gorgeous Plastic Pizza",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 78,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 33,
                            slug = "ut",
                            title = "Awesome Soft Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 79,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 83,
                            slug = "fugiat",
                            title = "Unbranded Cotton Towels",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 80,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 78,
                            slug = "quia",
                            title = "Rustic Steel Table",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 81,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 55,
                            slug = "dolor",
                            title = "Incredible Frozen Table",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 82,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 97,
                            slug = "ut",
                            title = "Small Soft Sausages",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 83,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 43,
                            slug = "est",
                            title = "Rustic Concrete Mouse",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 84,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 21,
                            slug = "minus",
                            title = "Gorgeous Fresh Car",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 85,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 36,
                            slug = "unde",
                            title = "Generic Metal Bike",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 86,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 63,
                            slug = "praesentium",
                            title = "Handmade Soft Chair",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 87,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 77,
                            slug = "vel",
                            title = "Awesome Rubber Table",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 88,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 32,
                            slug = "autem",
                            title = "Ergonomic Concrete Car",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 89,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 79,
                            slug = "officia",
                            title = "Practical Concrete Towels",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 90,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\",\"https://picsum.photos/640/480/?image=421\"]",
                            price = 23,
                            slug = "iure",
                            title = "Licensed Rubber Tuna",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 91,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 95,
                            slug = "dolorem",
                            title = "Handcrafted Granite Bike",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 92,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 65,
                            slug = "ipsum",
                            title = "Refined Frozen Salad",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 93,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 79,
                            slug = "velit",
                            title = "Rustic Cotton Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 94,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 55,
                            slug = "vero",
                            title = "Fantastic Soft Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 95,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 47,
                            slug = "necessitatibus",
                            title = "Sleek Granite Pizza",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 96,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 92,
                            slug = "distinctio",
                            title = "Intelligent Wooden Ball",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 97,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 97,
                            slug = "numquam",
                            title = "Refined Fresh Fish",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 98,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 25,
                            slug = "deleniti",
                            title = "Unbranded Concrete Gloves",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 99,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\",\"https://picsum.photos/640/480/?image=419\"]",
                            price = 67,
                            slug = "ad",
                            title = "Awesome Frozen Salad",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        },
                        new
                        {
                            id = 100,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=591\",\"https://picsum.photos/640/480/?image=36\"]",
                            price = 72,
                            slug = "voluptas",
                            title = "Unbranded Frozen Chair",
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        });
                });

            modelBuilder.Entity("ThalesApi.Domain.Models.Sesion", b =>
                {
                    b.Property<Guid>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SesionID");

                    b.Property<DateTime>("Expiration_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Expiration_Date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<DateTime>("creationAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SesionId");

                    b.HasIndex("UserId");

                    b.ToTable("Sesion");
                });

            modelBuilder.Entity("ThalesApi.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.Property<DateTime>("creationAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PasswordHash = "81DC9BDB52D04DC223B621240E3DD8B7",
                            Username = "Juan",
                            creationAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658),
                            updatedAt = new DateTime(2025, 3, 1, 21, 1, 38, 615, DateTimeKind.Utc).AddTicks(658)
                        });
                });

            modelBuilder.Entity("ThalesApi.Domain.Models.Product", b =>
                {
                    b.HasOne("ThalesApi.Domain.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("ThalesApi.Domain.Models.Sesion", b =>
                {
                    b.HasOne("ThalesApi.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
