// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThalesApi.Domain.DB;

#nullable disable

namespace ThalesApi.Domain.Migrations
{
    [DbContext(typeof(ThalesContext))]
    [Migration("20250301203859_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThalesApi.Domain.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("creationAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            image = "https://picsum.photos/640/480/?image=274",
                            name = "Technology",
                            slug = "aperiam",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            image = "https://picsum.photos/640/480/?image=130",
                            name = "Clothes",
                            slug = "dolorum",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            image = "https://picsum.photos/640/480/?image=889",
                            name = "Food",
                            slug = "qui",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            image = "https://picsum.photos/640/480/?image=920",
                            name = "House",
                            slug = "consequuntur",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            image = "https://picsum.photos/640/480/?image=698",
                            name = "Sport",
                            slug = "molestiae",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        });
                });

            modelBuilder.Entity("ThalesApi.Domain.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("creationAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 47,
                            slug = "at",
                            title = "Incredible Fresh Ball",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 2,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 67,
                            slug = "magni",
                            title = "Awesome Cotton Hat",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 3,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 51,
                            slug = "adipisci",
                            title = "Generic Metal Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 4,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 57,
                            slug = "voluptas",
                            title = "Gorgeous Granite Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 5,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 62,
                            slug = "maxime",
                            title = "Refined Cotton Tuna",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 6,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 80,
                            slug = "ipsum",
                            title = "Fantastic Metal Soap",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 7,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 69,
                            slug = "minus",
                            title = "Licensed Cotton Fish",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 8,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 59,
                            slug = "ea",
                            title = "Tasty Steel Computer",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 9,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 93,
                            slug = "sunt",
                            title = "Handmade Granite Computer",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 10,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 50,
                            slug = "dicta",
                            title = "Gorgeous Soft Keyboard",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 11,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 82,
                            slug = "sunt",
                            title = "Intelligent Soft Pants",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 12,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 27,
                            slug = "dolorem",
                            title = "Practical Rubber Chair",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 13,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 53,
                            slug = "qui",
                            title = "Gorgeous Fresh Soap",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 14,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 78,
                            slug = "aut",
                            title = "Practical Granite Pizza",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 15,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 78,
                            slug = "ipsa",
                            title = "Refined Soft Chips",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 16,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 37,
                            slug = "eveniet",
                            title = "Unbranded Fresh Car",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 17,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 33,
                            slug = "dolore",
                            title = "Sleek Rubber Pizza",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 18,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 47,
                            slug = "consectetur",
                            title = "Gorgeous Soft Tuna",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 19,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 96,
                            slug = "natus",
                            title = "Unbranded Cotton Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 20,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 40,
                            slug = "eum",
                            title = "Ergonomic Granite Chair",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 21,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 15,
                            slug = "quae",
                            title = "Rustic Soft Pizza",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 22,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 49,
                            slug = "aut",
                            title = "Refined Granite Pants",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 23,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 91,
                            slug = "nulla",
                            title = "Generic Metal Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 24,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 87,
                            slug = "esse",
                            title = "Awesome Rubber Table",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 25,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 21,
                            slug = "sint",
                            title = "Awesome Cotton Gloves",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 26,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 92,
                            slug = "nobis",
                            title = "Handcrafted Granite Cheese",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 27,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 29,
                            slug = "qui",
                            title = "Unbranded Soft Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 28,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 66,
                            slug = "quia",
                            title = "Handcrafted Granite Table",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 29,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 47,
                            slug = "non",
                            title = "Awesome Fresh Computer",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 30,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 62,
                            slug = "incidunt",
                            title = "Licensed Steel Mouse",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 31,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 33,
                            slug = "magni",
                            title = "Small Metal Bike",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 32,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 24,
                            slug = "fuga",
                            title = "Small Wooden Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 33,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 85,
                            slug = "minima",
                            title = "Generic Rubber Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 34,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 67,
                            slug = "tenetur",
                            title = "Handmade Steel Salad",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 35,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 16,
                            slug = "enim",
                            title = "Refined Cotton Computer",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 36,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 59,
                            slug = "reprehenderit",
                            title = "Unbranded Concrete Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 37,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 77,
                            slug = "voluptas",
                            title = "Gorgeous Frozen Car",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 38,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 67,
                            slug = "ut",
                            title = "Awesome Plastic Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 39,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 89,
                            slug = "est",
                            title = "Refined Fresh Hat",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 40,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 35,
                            slug = "est",
                            title = "Gorgeous Plastic Fish",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 41,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 49,
                            slug = "ipsum",
                            title = "Practical Metal Chips",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 42,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 61,
                            slug = "dicta",
                            title = "Ergonomic Frozen Pants",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 43,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 82,
                            slug = "est",
                            title = "Tasty Frozen Tuna",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 44,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 27,
                            slug = "fugit",
                            title = "Ergonomic Wooden Towels",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 45,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 26,
                            slug = "atque",
                            title = "Handcrafted Granite Computer",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 46,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 53,
                            slug = "vero",
                            title = "Handcrafted Wooden Shoes",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 47,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 90,
                            slug = "et",
                            title = "Handcrafted Concrete Table",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 48,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 95,
                            slug = "id",
                            title = "Incredible Metal Hat",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 49,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 62,
                            slug = "fugit",
                            title = "Practical Fresh Chips",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 50,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 71,
                            slug = "consequuntur",
                            title = "Small Rubber Fish",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 51,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 58,
                            slug = "deleniti",
                            title = "Tasty Metal Table",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 52,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 58,
                            slug = "distinctio",
                            title = "Gorgeous Plastic Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 53,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 66,
                            slug = "quas",
                            title = "Gorgeous Frozen Chicken",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 54,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 70,
                            slug = "vitae",
                            title = "Refined Frozen Ball",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 55,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 69,
                            slug = "sed",
                            title = "Fantastic Wooden Chips",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 56,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 50,
                            slug = "ipsa",
                            title = "Practical Granite Pants",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 57,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 88,
                            slug = "aut",
                            title = "Gorgeous Frozen Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 58,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 76,
                            slug = "dolore",
                            title = "Fantastic Concrete Pants",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 59,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 22,
                            slug = "nihil",
                            title = "Rustic Plastic Table",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 60,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 28,
                            slug = "quo",
                            title = "Intelligent Metal Fish",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 61,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 63,
                            slug = "temporibus",
                            title = "Handmade Rubber Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 62,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 35,
                            slug = "repellendus",
                            title = "Ergonomic Concrete Chicken",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 63,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 68,
                            slug = "eligendi",
                            title = "Tasty Plastic Keyboard",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 64,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 46,
                            slug = "rerum",
                            title = "Fantastic Concrete Fish",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 65,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 65,
                            slug = "repellendus",
                            title = "Sleek Soft Mouse",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 66,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 32,
                            slug = "pariatur",
                            title = "Gorgeous Frozen Pizza",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 67,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 63,
                            slug = "quia",
                            title = "Licensed Rubber Chair",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 68,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 48,
                            slug = "dolores",
                            title = "Fantastic Plastic Bacon",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 69,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 44,
                            slug = "distinctio",
                            title = "Practical Steel Mouse",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 70,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 59,
                            slug = "qui",
                            title = "Unbranded Concrete Chips",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 71,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 76,
                            slug = "possimus",
                            title = "Small Cotton Bike",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 72,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 83,
                            slug = "voluptas",
                            title = "Small Steel Tuna",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 73,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 59,
                            slug = "odit",
                            title = "Handmade Frozen Keyboard",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 74,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 24,
                            slug = "aliquam",
                            title = "Gorgeous Fresh Fish",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 75,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 71,
                            slug = "dicta",
                            title = "Licensed Wooden Table",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 76,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 36,
                            slug = "voluptate",
                            title = "Small Soft Fish",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 77,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 94,
                            slug = "est",
                            title = "Generic Granite Keyboard",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 78,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 24,
                            slug = "eos",
                            title = "Handcrafted Concrete Fish",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 79,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Football Is Good For Training And Recreational Purposes",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 90,
                            slug = "maxime",
                            title = "Unbranded Soft Keyboard",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 80,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 53,
                            slug = "quaerat",
                            title = "Handmade Wooden Bike",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 81,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 73,
                            slug = "dolorum",
                            title = "Awesome Frozen Bike",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 82,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 64,
                            slug = "enim",
                            title = "Intelligent Fresh Car",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 83,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 98,
                            slug = "consequatur",
                            title = "Incredible Steel Ball",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 84,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 54,
                            slug = "vitae",
                            title = "Sleek Frozen Tuna",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 85,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 46,
                            slug = "ad",
                            title = "Practical Steel Shirt",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 86,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 32,
                            slug = "voluptatibus",
                            title = "Gorgeous Frozen Chips",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 87,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 93,
                            slug = "expedita",
                            title = "Awesome Plastic Tuna",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 88,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 55,
                            slug = "necessitatibus",
                            title = "Ergonomic Fresh Mouse",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 89,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 52,
                            slug = "quae",
                            title = "Awesome Frozen Mouse",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 90,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 21,
                            slug = "quis",
                            title = "Handmade Wooden Pants",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 91,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 72,
                            slug = "autem",
                            title = "Rustic Frozen Ball",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 92,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 66,
                            slug = "voluptas",
                            title = "Small Rubber Keyboard",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 93,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 34,
                            slug = "voluptatem",
                            title = "Ergonomic Rubber Pizza",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 94,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 64,
                            slug = "sit",
                            title = "Incredible Frozen Bike",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 95,
                            categoryId = 5,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 63,
                            slug = "deleniti",
                            title = "Sleek Fresh Hat",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 96,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 47,
                            slug = "ipsum",
                            title = "Sleek Cotton Hat",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 97,
                            categoryId = 4,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 35,
                            slug = "dicta",
                            title = "Intelligent Steel Towels",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 98,
                            categoryId = 1,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\",\"https://picsum.photos/640/480/?image=705\"]",
                            price = 30,
                            slug = "totam",
                            title = "Rustic Frozen Pizza",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 99,
                            categoryId = 3,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\",\"https://picsum.photos/640/480/?image=445\"]",
                            price = 16,
                            slug = "voluptas",
                            title = "Small Concrete Gloves",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        },
                        new
                        {
                            id = 100,
                            categoryId = 2,
                            creationAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826),
                            description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            images = "[\"https://picsum.photos/640/480/?image=261\",\"https://picsum.photos/640/480/?image=492\"]",
                            price = 52,
                            slug = "vel",
                            title = "Ergonomic Concrete Chips",
                            updatedAt = new DateTime(2025, 3, 1, 20, 38, 58, 341, DateTimeKind.Utc).AddTicks(826)
                        });
                });

            modelBuilder.Entity("ThalesApi.Domain.Models.Product", b =>
                {
                    b.HasOne("ThalesApi.Domain.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
